import type { Framework, ScanResult, DetectedEndpoint } from '../types'

/**
 * Generate the content of a fixtures file from scan results.
 */
export function generateFixturesFile(
  scanResult: ScanResult,
  framework: Framework
): string {
  const { endpoints } = scanResult

  if (endpoints.length === 0) {
    return generateEmptyFixtures(framework)
  }

  const lines: string[] = [
    `import type { FixtureMap } from '@demokit-ai/core'`,
    '',
    '/**',
    ' * Demo fixtures generated by create-demokit.',
    ' * Edit this file to customize your demo data.',
    ' */',
    '',
  ]

  // Generate sample data constants if we have GET list endpoints
  const listEndpoints = endpoints.filter(
    (ep) => ep.method === 'GET' && !ep.path.includes(':')
  )

  if (listEndpoints.length > 0) {
    lines.push('// Sample demo data')
    for (const ep of listEndpoints) {
      const name = endpointToVarName(ep)
      const sample = generateSampleData(ep)
      lines.push(`const ${name} = ${JSON.stringify(sample, null, 2)}`)
      lines.push('')
    }
  }

  // Generate the fixture map
  lines.push('export const fixtures: FixtureMap = {')

  for (const ep of endpoints) {
    const handler = generateHandler(ep, endpoints)
    lines.push(`  '${ep.method} ${ep.path}': ${handler},`)
    lines.push('')
  }

  lines.push('}')
  lines.push('')

  // Generate empty-state scenario
  lines.push('/**')
  lines.push(' * Empty-state scenario: shows the app with no data.')
  lines.push(' */')
  lines.push('export const emptyFixtures: FixtureMap = {')

  for (const ep of endpoints) {
    if (ep.method === 'GET') {
      const isDetail = ep.path.includes(':')
      lines.push(`  '${ep.method} ${ep.path}': ${isDetail ? '() => null' : '() => []'},`)
    }
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function generateEmptyFixtures(framework: Framework): string {
  return `import type { FixtureMap } from '@demokit-ai/core'

/**
 * Demo fixtures for your app.
 *
 * No API endpoints were auto-detected. Add your fixtures manually:
 *
 * export const fixtures: FixtureMap = {
 *   'GET /api/users': () => [
 *     { id: '1', name: 'Demo User', email: 'demo@example.com' },
 *   ],
 *   'GET /api/users/:id': ({ params }) => ({
 *     id: params.id,
 *     name: 'Demo User',
 *     email: 'demo@example.com',
 *   }),
 *   'POST /api/users': ({ body }) => ({
 *     id: crypto.randomUUID(),
 *     ...body,
 *   }),
 * }
 *
 * Then activate demo mode by visiting any page with ?demo=true
 */
export const fixtures: FixtureMap = {
  // Add your fixture definitions here
}
`
}

function endpointToVarName(ep: DetectedEndpoint): string {
  // /api/users -> DEMO_USERS, /api/products -> DEMO_PRODUCTS
  const segments = ep.path.split('/').filter(Boolean)
  const last = segments[segments.length - 1] ?? 'data'
  return `DEMO_${last.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`
}

function generateSampleData(ep: DetectedEndpoint): unknown[] {
  const resource = guessResourceName(ep.path)

  // Generate 3 sample records based on resource name
  switch (resource) {
    case 'users':
      return [
        { id: '1', name: 'Alice Johnson', email: 'alice@demo.com', role: 'admin' },
        { id: '2', name: 'Bob Smith', email: 'bob@demo.com', role: 'member' },
        { id: '3', name: 'Carol Williams', email: 'carol@demo.com', role: 'member' },
      ]
    case 'products':
      return [
        { id: '1', name: 'Wireless Headphones', price: 79.99, status: 'active' },
        { id: '2', name: 'USB-C Hub', price: 49.99, status: 'active' },
        { id: '3', name: 'Mechanical Keyboard', price: 149.99, status: 'active' },
      ]
    case 'orders':
      return [
        { id: '1', status: 'delivered', total: 129.98, created_at: '2024-12-15T10:30:00Z' },
        { id: '2', status: 'shipped', total: 49.99, created_at: '2024-12-18T14:00:00Z' },
        { id: '3', status: 'pending', total: 229.97, created_at: '2024-12-20T09:15:00Z' },
      ]
    default:
      return [
        { id: '1', name: `Demo ${resource} 1` },
        { id: '2', name: `Demo ${resource} 2` },
        { id: '3', name: `Demo ${resource} 3` },
      ]
  }
}

function guessResourceName(path: string): string {
  const segments = path.split('/').filter((s) => s && !s.startsWith(':') && s !== 'api')
  return segments[segments.length - 1] ?? 'items'
}

function generateHandler(ep: DetectedEndpoint, allEndpoints: DetectedEndpoint[]): string {
  const resource = guessResourceName(ep.path)
  const varName = `DEMO_${resource.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`
  const isDetail = ep.path.includes(':')

  switch (ep.method) {
    case 'GET':
      if (isDetail) {
        // Check if there's a list endpoint with the same data
        const listExists = allEndpoints.some(
          (e) => e.method === 'GET' && e.path === ep.path.replace(/\/:[\w]+$/, '')
        )
        if (listExists) {
          return `({ params }) => ${varName}.find(item => item.id === params.id) ?? ${varName}[0]`
        }
        return `({ params }) => ({ id: params.id, name: 'Demo ${resource}' })`
      }
      return `() => ${varName}`

    case 'POST':
      return `({ body }) => ({ id: crypto.randomUUID(), ...body, created_at: new Date().toISOString() })`

    case 'PUT':
    case 'PATCH':
      return `({ params, body }) => ({ id: params.id, ...body, updated_at: new Date().toISOString() })`

    case 'DELETE':
      return `({ params }) => ({ id: params.id, deleted: true })`

    default:
      return `() => ({ ok: true })`
  }
}

/**
 * Get the file path where fixtures should be placed, relative to project root.
 */
export function getFixturesPath(framework: Framework): string {
  switch (framework) {
    case 'react':
      return 'src/demo/fixtures.ts'
  }
}
