import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseQueryOptions,
} from '@tanstack/react-query'
import type {
  CreateEndpointMappingInput,
  UpdateEndpointMappingInput,
} from '@/lib/api/schemas'

// Types matching the database schema
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type ResponseType = 'collection' | 'single' | 'custom'
export type MappingStatus = 'valid' | 'corrected' | 'flagged' | 'disabled'

export interface EndpointMapping {
  id: string
  fixtureId: string
  method: HttpMethod
  pattern: string
  sourceModel: string
  responseType: ResponseType
  lookupField: string | null
  lookupParam: string | null
  transformCode: string | null
  status: MappingStatus
  originalSourceModel: string | null
  validationReason: string | null
  confidence: number | null
  isAutoGenerated: boolean
  isEnabled: boolean
  priority: number
  createdAt: string
  updatedAt: string
}

// ============================================================================
// Fetch Functions
// ============================================================================

async function fetchEndpointMappings(
  projectId: string,
  fixtureId: string
): Promise<EndpointMapping[]> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings`
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to fetch endpoint mappings')
  }
  return res.json()
}

async function fetchEndpointMapping(
  projectId: string,
  fixtureId: string,
  mappingId: string
): Promise<EndpointMapping> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings/${mappingId}`
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to fetch endpoint mapping')
  }
  return res.json()
}

async function createEndpointMapping({
  projectId,
  fixtureId,
  data,
}: {
  projectId: string
  fixtureId: string
  data: CreateEndpointMappingInput
}): Promise<EndpointMapping> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    }
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to create endpoint mapping')
  }
  return res.json()
}

async function createBulkEndpointMappings({
  projectId,
  fixtureId,
  mappings,
}: {
  projectId: string
  fixtureId: string
  mappings: CreateEndpointMappingInput[]
}): Promise<EndpointMapping[]> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mappings }),
    }
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to create endpoint mappings')
  }
  return res.json()
}

async function updateEndpointMapping({
  projectId,
  fixtureId,
  mappingId,
  data,
}: {
  projectId: string
  fixtureId: string
  mappingId: string
  data: UpdateEndpointMappingInput
}): Promise<EndpointMapping> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings/${mappingId}`,
    {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    }
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to update endpoint mapping')
  }
  return res.json()
}

async function deleteEndpointMapping({
  projectId,
  fixtureId,
  mappingId,
}: {
  projectId: string
  fixtureId: string
  mappingId: string
}): Promise<void> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings/${mappingId}`,
    { method: 'DELETE' }
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to delete endpoint mapping')
  }
}

async function deleteAllEndpointMappings({
  projectId,
  fixtureId,
}: {
  projectId: string
  fixtureId: string
}): Promise<void> {
  const res = await fetch(
    `/api/projects/${projectId}/fixtures/${fixtureId}/mappings`,
    { method: 'DELETE' }
  )
  if (!res.ok) {
    const error = await res.json()
    throw new Error(error.error || 'Failed to delete endpoint mappings')
  }
}

// ============================================================================
// Query Keys
// ============================================================================

export const endpointMappingKeys = {
  all: ['endpoint-mappings'] as const,
  lists: () => [...endpointMappingKeys.all, 'list'] as const,
  list: (projectId: string, fixtureId: string) =>
    [...endpointMappingKeys.lists(), projectId, fixtureId] as const,
  details: () => [...endpointMappingKeys.all, 'detail'] as const,
  detail: (projectId: string, fixtureId: string, mappingId: string) =>
    [...endpointMappingKeys.details(), projectId, fixtureId, mappingId] as const,
}

// ============================================================================
// Query Hooks
// ============================================================================

export function useEndpointMappings(
  projectId: string,
  fixtureId: string,
  options?: Omit<
    UseQueryOptions<EndpointMapping[], Error>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery({
    queryKey: endpointMappingKeys.list(projectId, fixtureId),
    queryFn: () => fetchEndpointMappings(projectId, fixtureId),
    enabled: !!projectId && !!fixtureId,
    ...options,
  })
}

export function useEndpointMapping(
  projectId: string,
  fixtureId: string,
  mappingId: string,
  options?: Omit<UseQueryOptions<EndpointMapping, Error>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: endpointMappingKeys.detail(projectId, fixtureId, mappingId),
    queryFn: () => fetchEndpointMapping(projectId, fixtureId, mappingId),
    enabled: !!projectId && !!fixtureId && !!mappingId,
    ...options,
  })
}

// ============================================================================
// Mutation Hooks
// ============================================================================

export function useCreateEndpointMapping(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: CreateEndpointMappingInput) =>
      createEndpointMapping({ projectId, fixtureId, data }),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
    },
  })
}

export function useCreateBulkEndpointMappings(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (mappings: CreateEndpointMappingInput[]) =>
      createBulkEndpointMappings({ projectId, fixtureId, mappings }),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
    },
  })
}

export function useUpdateEndpointMapping(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ mappingId, data }: { mappingId: string; data: UpdateEndpointMappingInput }) =>
      updateEndpointMapping({ projectId, fixtureId, mappingId, data }),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.detail(projectId, fixtureId, variables.mappingId),
      })
    },
  })
}

export function useDeleteEndpointMapping(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (mappingId: string) =>
      deleteEndpointMapping({ projectId, fixtureId, mappingId }),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
    },
  })
}

export function useDeleteAllEndpointMappings(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: () =>
      deleteAllEndpointMappings({ projectId, fixtureId }),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
    },
  })
}

// ============================================================================
// Toggle Hook (convenience for enabling/disabling)
// ============================================================================

export function useToggleEndpointMapping(projectId: string, fixtureId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async ({ mappingId, isEnabled }: { mappingId: string; isEnabled: boolean }) => {
      return updateEndpointMapping({
        projectId,
        fixtureId,
        mappingId,
        data: { isEnabled },
      })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: endpointMappingKeys.list(projectId, fixtureId),
      })
    },
  })
}
