/**
 * MappingEditor Component
 *
 * Dialog for creating and editing endpoint mappings.
 */

import React, { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import {
  useCreateEndpointMapping,
  useUpdateEndpointMapping,
  type EndpointMapping,
  type HttpMethod,
  type ResponseType,
} from "@/hooks/use-endpoint-mappings";
import { Loader2 } from "lucide-react";

const HTTP_METHODS: HttpMethod[] = ["GET", "POST", "PUT", "PATCH", "DELETE"];
const RESPONSE_TYPES: ResponseType[] = ["collection", "single", "custom"];

interface FormState {
  method: HttpMethod;
  pattern: string;
  sourceModel: string;
  responseType: ResponseType;
  lookupField: string;
  lookupParam: string;
  transformCode: string;
  isAutoGenerated: boolean;
  priority: number;
}

interface FormErrors {
  pattern?: string;
  sourceModel?: string;
}

const defaultFormState: FormState = {
  method: "GET",
  pattern: "/api/",
  sourceModel: "",
  responseType: "collection",
  lookupField: "",
  lookupParam: "",
  transformCode: "",
  isAutoGenerated: false,
  priority: 0,
};

export interface MappingEditorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: string;
  fixtureId: string;
  mapping: EndpointMapping | null;
  availableModels: string[];
}

export function MappingEditor({
  open,
  onOpenChange,
  projectId,
  fixtureId,
  mapping,
  availableModels,
}: MappingEditorProps) {
  const isEditing = mapping !== null;

  const createMutation = useCreateEndpointMapping(projectId, fixtureId);
  const updateMutation = useUpdateEndpointMapping(projectId, fixtureId);

  const [form, setForm] = useState<FormState>(defaultFormState);
  const [errors, setErrors] = useState<FormErrors>({});

  // Reset form when mapping changes
  useEffect(() => {
    if (mapping) {
      setForm({
        method: mapping.method,
        pattern: mapping.pattern,
        sourceModel: mapping.sourceModel,
        responseType: mapping.responseType,
        lookupField: mapping.lookupField || "",
        lookupParam: mapping.lookupParam || "",
        transformCode: mapping.transformCode || "",
        isAutoGenerated: mapping.isAutoGenerated,
        priority: mapping.priority,
      });
    } else {
      setForm({
        ...defaultFormState,
        sourceModel: availableModels[0] || "",
      });
    }
    setErrors({});
  }, [mapping, availableModels]);

  const isPending = createMutation.isPending || updateMutation.isPending;

  const updateField = <K extends keyof FormState>(
    field: K,
    value: FormState[K]
  ) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    // Clear error when field is updated
    if (field in errors) {
      setErrors((prev) => ({ ...prev, [field]: undefined }));
    }
  };

  const validate = (): boolean => {
    const newErrors: FormErrors = {};

    if (!form.pattern || !form.pattern.startsWith("/")) {
      newErrors.pattern = "Pattern must start with /";
    }

    if (!form.sourceModel) {
      newErrors.sourceModel = "Source model is required";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) return;

    const payload = {
      method: form.method,
      pattern: form.pattern,
      sourceModel: form.sourceModel,
      responseType: form.responseType,
      lookupField: form.lookupField || null,
      lookupParam: form.lookupParam || null,
      transformCode: form.transformCode || null,
      isAutoGenerated: form.isAutoGenerated,
      priority: form.priority,
    };

    if (isEditing && mapping) {
      await updateMutation.mutateAsync({
        mappingId: mapping.id,
        data: payload,
      });
    } else {
      await createMutation.mutateAsync(payload);
    }

    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>
            {isEditing ? "Edit Endpoint Mapping" : "Add Endpoint Mapping"}
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Method and Pattern */}
          <div className="flex gap-3">
            <div className="w-28">
              <Label htmlFor="method" className="text-xs">
                Method
              </Label>
              <Select
                value={form.method}
                onValueChange={(value: HttpMethod) =>
                  updateField("method", value)
                }
              >
                <SelectTrigger id="method" className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {HTTP_METHODS.map((method) => (
                    <SelectItem key={method} value={method}>
                      {method}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex-1">
              <Label htmlFor="pattern" className="text-xs">
                URL Pattern
              </Label>
              <Input
                id="pattern"
                placeholder="/api/users/:id"
                className="mt-1 font-mono text-sm"
                value={form.pattern}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField("pattern", e.target.value)}
              />
              {errors.pattern && (
                <p className="text-xs text-destructive mt-1">{errors.pattern}</p>
              )}
            </div>
          </div>

          {/* Source Model and Response Type */}
          <div className="flex gap-3">
            <div className="flex-1">
              <Label htmlFor="sourceModel" className="text-xs">
                Source Model
              </Label>
              <Select
                value={form.sourceModel}
                onValueChange={(value) => updateField("sourceModel", value)}
              >
                <SelectTrigger id="sourceModel" className="mt-1">
                  <SelectValue placeholder="Select model" />
                </SelectTrigger>
                <SelectContent>
                  {availableModels.map((model) => (
                    <SelectItem key={model} value={model}>
                      {model}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.sourceModel && (
                <p className="text-xs text-destructive mt-1">
                  {errors.sourceModel}
                </p>
              )}
            </div>

            <div className="w-36">
              <Label htmlFor="responseType" className="text-xs">
                Response Type
              </Label>
              <Select
                value={form.responseType}
                onValueChange={(value: ResponseType) =>
                  updateField("responseType", value)
                }
              >
                <SelectTrigger id="responseType" className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {RESPONSE_TYPES.map((type) => (
                    <SelectItem key={type} value={type}>
                      {type}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Lookup fields for single response type */}
          {form.responseType === "single" && (
            <div className="flex gap-3 p-3 bg-muted/30 rounded-md">
              <div className="flex-1">
                <Label htmlFor="lookupField" className="text-xs">
                  Lookup Field
                </Label>
                <Input
                  id="lookupField"
                  placeholder="id"
                  className="mt-1 font-mono text-sm"
                  value={form.lookupField}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField("lookupField", e.target.value)}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Field in model to match against
                </p>
              </div>

              <div className="flex-1">
                <Label htmlFor="lookupParam" className="text-xs">
                  URL Param
                </Label>
                <Input
                  id="lookupParam"
                  placeholder="id"
                  className="mt-1 font-mono text-sm"
                  value={form.lookupParam}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField("lookupParam", e.target.value)}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  URL parameter name (e.g., :id)
                </p>
              </div>
            </div>
          )}

          {/* Transform code for custom response type */}
          {form.responseType === "custom" && (
            <div className="p-3 bg-muted/30 rounded-md">
              <Label htmlFor="transformCode" className="text-xs">
                Transform Code (JavaScript)
              </Label>
              <Textarea
                id="transformCode"
                placeholder={`// ({ data, params, query }) => { return data.slice(0, 10); }`}
                className="mt-1 font-mono text-sm min-h-[80px]"
                value={form.transformCode}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateField("transformCode", e.target.value)}
              />
              <p className="text-xs text-muted-foreground mt-1">
                Custom transform function for complex responses
              </p>
            </div>
          )}

          {/* Priority */}
          <div className="flex items-center justify-between p-3 bg-muted/30 rounded-md">
            <div>
              <Label htmlFor="priority" className="text-xs">
                Priority
              </Label>
              <p className="text-xs text-muted-foreground">
                Higher priority mappings are matched first
              </p>
            </div>
            <Input
              id="priority"
              type="number"
              min={0}
              className="w-20 text-center"
              value={form.priority}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                updateField("priority", parseInt(e.target.value) || 0)
              }
            />
          </div>

          {/* Auto-generated flag (for editing) */}
          {isEditing && mapping?.isAutoGenerated && (
            <div className="flex items-center gap-2 p-3 bg-primary/5 rounded-md text-sm">
              <span className="text-muted-foreground">
                This mapping was auto-generated from schema
              </span>
            </div>
          )}

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isPending}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isPending}>
              {isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              {isEditing ? "Save Changes" : "Create Mapping"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
