/**
 * Demo fixtures for app
 * Generated by DemoKit Cloud
 *
 * These fixtures define the demo data that will be returned
 * when your app makes API requests in demo mode.
 */

import type { FixtureMap } from '@demokit-ai/core'

const DEMO_ORDER = [
  {
    "id": "2ca33c06-d39c-4cce-b228-96e4635b7aff",
    "items": [
      {
        "quantity": 1,
        "product_id": "550e8400-e29b-41d4-a716-446655440001"
      },
      {
        "quantity": 1,
        "product_id": "550e8400-e29b-41d4-a716-446655440004"
      }
    ],
    "status": "delivered",
    "created_at": "2024-01-20T14:30:00Z",
    "total_amount": 2049.98
  },
  {
    "id": "ed75c354-5bd9-4601-bbd5-3b9641369c34",
    "items": [
      {
        "quantity": 2,
        "product_id": "550e8400-e29b-41d4-a716-446655440003"
      }
    ],
    "status": "shipped",
    "created_at": "2024-01-22T09:15:00Z",
    "total_amount": 399.98
  },
  {
    "id": "be80b1a3-2e20-468f-8122-de63c5c2e7ab",
    "items": [
      {
        "quantity": 1,
        "product_id": "550e8400-e29b-41d4-a716-446655440002"
      },
      {
        "quantity": 2,
        "product_id": "550e8400-e29b-41d4-a716-446655440005"
      }
    ],
    "status": "confirmed",
    "created_at": "2024-01-25T16:45:00Z",
    "total_amount": 1349.97
  },
  {
    "id": "3f0a12b0-9962-40bb-a91c-23d68095f321",
    "items": [
      {
        "quantity": 1,
        "product_id": "550e8400-e29b-41d4-a716-446655440001"
      }
    ],
    "status": "pending",
    "created_at": "2024-01-26T11:20:00Z",
    "total_amount": 1999.99
  },
  {
    "id": "7458fe3e-9249-4281-93bf-bd72794ac354",
    "items": [
      {
        "quantity": 3,
        "product_id": "550e8400-e29b-41d4-a716-446655440005"
      },
      {
        "quantity": 1,
        "product_id": "550e8400-e29b-41d4-a716-446655440003"
      }
    ],
    "status": "confirmed",
    "created_at": "2024-01-27T13:10:00Z",
    "total_amount": 274.96
  }
] as const

const DEMO_ADDRESS = [
  {
    "city": "San Francisco",
    "line1": "123 Market Street",
    "line2": "Apt 4B",
    "state": "CA",
    "country": "USA",
    "postal_code": "94102"
  },
  {
    "city": "New York",
    "line1": "456 Broadway",
    "state": "NY",
    "country": "USA",
    "postal_code": "10013"
  },
  {
    "city": "Austin",
    "line1": "789 Congress Ave",
    "line2": "Suite 200",
    "state": "TX",
    "country": "USA",
    "postal_code": "78701"
  },
  {
    "city": "Seattle",
    "line1": "321 Pine Street",
    "state": "WA",
    "country": "USA",
    "postal_code": "98101"
  },
  {
    "city": "Chicago",
    "line1": "654 Michigan Ave",
    "line2": "Floor 12",
    "state": "IL",
    "country": "USA",
    "postal_code": "60611"
  }
] as const

const DEMO_PRODUCT = [
  {
    "id": "b413498c-f14c-4c03-aac0-dfc25ed4311f",
    "name": "MacBook Pro 14-inch M3",
    "price": 1999.99,
    "stock": 15,
    "category": "Electronics",
    "image_url": "https://example.com/images/macbook-pro-14.jpg",
    "created_at": "2024-01-15T10:00:00Z",
    "updated_at": "2024-01-15T10:00:00Z",
    "description": "Apple MacBook Pro 14-inch with M3 chip, 8GB RAM, 512GB SSD. Perfect for professional work and creative projects."
  },
  {
    "id": "73a15e65-66d6-4e42-81d0-09578390e2ad",
    "name": "Dell XPS 13 Plus",
    "price": 1299.99,
    "stock": 22,
    "category": "Electronics",
    "image_url": "https://example.com/images/dell-xps-13.jpg",
    "created_at": "2024-01-10T14:30:00Z",
    "updated_at": "2024-01-10T14:30:00Z",
    "description": "Dell XPS 13 Plus with Intel Core i7, 16GB RAM, 1TB SSD. Ultra-portable design with stunning display."
  },
  {
    "id": "e8b2f4ba-897b-43b0-af33-0552b3c3d344",
    "name": "Wireless Bluetooth Headphones",
    "price": 199.99,
    "stock": 45,
    "category": "Electronics",
    "image_url": "https://example.com/images/bluetooth-headphones.jpg",
    "created_at": "2024-01-08T09:15:00Z",
    "updated_at": "2024-01-08T09:15:00Z",
    "description": "Premium wireless headphones with active noise cancellation and 30-hour battery life."
  },
  {
    "id": "2ee21613-ee15-4b2e-a4b5-ad66a67a39fa",
    "name": "USB-C Hub 7-in-1",
    "price": 49.99,
    "stock": 78,
    "category": "Electronics",
    "image_url": "https://example.com/images/usb-c-hub.jpg",
    "created_at": "2024-01-05T16:45:00Z",
    "updated_at": "2024-01-05T16:45:00Z",
    "description": "Versatile USB-C hub with HDMI, USB 3.0 ports, SD card reader, and power delivery support."
  },
  {
    "id": "fee88cc9-166f-4b32-9c65-2b91c39fadb7",
    "name": "Portable Phone Stand",
    "price": 24.99,
    "stock": 120,
    "category": "Accessories",
    "image_url": "https://example.com/images/phone-stand.jpg",
    "created_at": "2024-01-03T11:20:00Z",
    "updated_at": "2024-01-03T11:20:00Z",
    "description": "Adjustable aluminum phone stand compatible with all smartphone sizes. Perfect for video calls and media viewing."
  }
] as const

const DEMO_CART_ITEM = [
  {
    "quantity": 1,
    "product_id": "b413498c-f14c-4c03-aac0-dfc25ed4311f"
  },
  {
    "quantity": 2,
    "product_id": "73a15e65-66d6-4e42-81d0-09578390e2ad"
  },
  {
    "quantity": 1,
    "product_id": "e8b2f4ba-897b-43b0-af33-0552b3c3d344"
  },
  {
    "quantity": 3,
    "product_id": "2ee21613-ee15-4b2e-a4b5-ad66a67a39fa"
  },
  {
    "quantity": 1,
    "product_id": "fee88cc9-166f-4b32-9c65-2b91c39fadb7"
  }
] as const

export const fixtures: FixtureMap = {
  // Order endpoints
  'GET /api/order': () => DEMO_ORDER,

  'GET /api/order/:id': ({ params }) => {
    return DEMO_ORDER.find((item) => item.id === params.id) || null
  },

  // Address endpoints
  'GET /api/address': () => DEMO_ADDRESS,

  'GET /api/address/:id': ({ params }) => {
    return DEMO_ADDRESS.find((item) => item.id === params.id) || null
  },

  // Product endpoints
  'GET /api/product': () => DEMO_PRODUCT,

  'GET /api/product/:id': ({ params }) => {
    return DEMO_PRODUCT.find((item) => item.id === params.id) || null
  },

  // CartItem endpoints
  'GET /api/cart-item': () => DEMO_CART_ITEM,

  'GET /api/cart-item/:id': ({ params }) => {
    return DEMO_CART_ITEM.find((item) => item.id === params.id) || null
  },

}
